### ISSUE TITLE
CMake: could not load cache

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/hipSPARSELt#71]
Following the CMake install guide (https://rocm.docs.amd.com/projects/hipSPARSELt/en/latest/Linux_Install_Guide.html)
I got the following error. Could you reproduce the error ?  Thanks.

hipSPARSELt/build/release/deps[develop]$ make -j install
[ 12%] Creating directories for 'lapack'
[ 25%] Performing download step (git clone) for 'lapack'
Cloning into 'lapack'...
Switched to a new branch 'lapack-3.7.1'
Branch 'lapack-3.7.1' set up to track remote branch 'lapack-3.7.1' from 'origin'.
[ 37%] Performing update step for 'lapack'
[ 50%] No patch step for 'lapack'
[ 62%] Performing configure step for 'lapack'
[ 87%] No install step for 'lapack'
[100%] Completed 'lapack'
[100%] Built target lapack
Error: could not load cache
make[3]: *** [CMakeFiles/install.dir/build.make:70: CMakeFiles/install] Error 1
make[2]: *** [CMakeFiles/Makefile2:138: CMakeFiles/install.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:145: CMakeFiles/install.dir/rule] Error 2

**Comment by ppanchad-amd** [comment]
Hi @jinz2014, internal ticket has been created to investigate your issue. Thanks!

**Comment by tcgu-amd** [comment]
Hi @jinz2014 Thank you for reporting the issue and sorry of the lack of response. Would you be able to provide more details on the system specs & the version of ROCm you are trying to build for? (By the way, the link you provided seems to be dead likely due to recent updates to the docs.) Meanwhile, we will try to reproduce the issue on the latest version.

On a side note, have you tried running the make command with sudo? It might help resolve your issue.

Thanks!

**Comment by tcgu-amd** [comment]
Hi @jinz2014 Unfortunately we couldn't reproduce the error on Ubuntu 24.04 with ROCm 6.2. It would be really helpful if you could send us more details regarding your system configuration. Another thing might help is to run `make clean` before running `make -j install`. Hope this can help. Thanks!

**Comment by jinz2014** [comment]
Thank you for your answers.
