### ISSUE TITLE
msgpack not detected after installed

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/hipSPARSELt#72]
cmake ../..

Installing collected packages: pyyaml, msgpack, joblib, Tensile
**Successfully installed Tensile-4.33.0 joblib-1.3.2 msgpack-1.0.7 pyyaml-6.0.1**
-- using GIT Tensile fork=ROCmSoftwarePlatform from branch=7d55e43f96870b49384c546bae3b66e9bc0c740b
-- Adding /path/to/hipSPARSELt/build/release/virtualenv to CMAKE_PREFIX_PATH
-- hip::amdhip64 is SHARED_LIBRARY
CMake Error at build/release/virtualenv/lib/python3.11/site-packages/Tensile/Source/lib/CMakeLists.txt:105 (find_package):
  By not providing "Findmsgpack.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "msgpack", but
  CMake did not find one.

  Could not find a package configuration file provided by "msgpack" with any
  of the following names:

    msgpackConfig.cmake
    msgpack-config.cmake

  Add the installation prefix of "msgpack" to CMAKE_PREFIX_PATH or set
  "msgpack_DIR" to a directory containing one of the above files.  If
  "msgpack" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by nachiketkarmarkar** [comment]
I encountered this same error as I tried compiling rocBLAS

**Comment by ppanchad-amd** [comment]
Hi @jinz2014, internal ticket has been created to investigate your issue. Thanks!

**Comment by jamesxu2** [comment]
Hi @jinz2014 , this is an issue with the install script not installing the msgpack dependency. You can get around this by installing **libmsgpack-dev** (on Ubuntu).

There is also another missing dependency that is needed for tensile, so you'll need to install **python3-joblib** as well.

The installer script will be updated in a future release to automatically install these dependencies. Thanks for finding this out!

---

@nachiketkarmarkar rocBLAS is a different library, in future, please open issues in the relevant repo rather than attaching them to existing related issues. If you want, you could tag related-looking issues with a hyperlink to help our investigation.

That being said, I think you will be able to compile rocBLAS if you run the dependency installer first as recommended on the docs: https://rocm.docs.amd.com/projects/rocBLAS/en/latest/install/Linux_Install_Guide.html#linux-install

Quoting those docs:
> ./install.sh -d | Build library dependencies and library in your local directory. The -d` flag only needs to be used once. For subsequent invocations of install.sh` it is not necessary to rebuild the dependencies.

> ./install.sh | Build library in your local directory. **It is assumed dependencies have been built**

The rocBLAS installer script when run with ```-d``` will in fact install the python3-joblib and libmsgpack-dev libraries, among other dependencies.

I did observe the same "msgpack not detected" error when I just ran the install script without building dependencies first.

**Comment by jamesxu2** [comment]
@jinz2014 The missing dependency fix was merged in https://github.com/ROCm/hipSPARSELt/pull/151/files.
